# Generated by Django 5.2.17 on 2026-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('voice', 'Voice clip'), ('url', 'URL'), ('message', 'Message')], default='voice', max_length=10)),
                ('label', models.CharField(help_text='Filename, URL or sender', max_length=200)),
                ('source', models.CharField(blank=True, help_text='phone, browser, existing...', max_length=40)),
                ('score', models.FloatField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=40)),
                ('risk', models.CharField(blank=True, max_length=10)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('model_eer', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('media_url', models.CharField(blank=True, max_length=400)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
