# Generated by Django 5.2.17 on 2026-09-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0002_forensicreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mother, Dad, Priya...', max_length=80)),
                ('relation', models.CharField(blank=True, max_length=60)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('audio_path', models.CharField(max_length=400)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('embedding', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('severity', models.CharField(default='HIGH', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField(blank=True)),
                ('seen', models.BooleanField(default=False)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cyber.forensicreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
